# build stage
FROM python:3.11 AS builder

# install PDM
RUN pip install -U pip setuptools wheel
RUN pip install pdm

# copy files
COPY pyproject.toml pdm.lock /project/
COPY src/ /project/src

# install dependencies and project into the local packages directory
WORKDIR /project
RUN pdm sync --prod --no-editable


# run stage
FROM python:3.11-slim

RUN pip install pdm

WORKDIR /project

# retrieve packages from build stage
COPY --from=builder /project/.venv /project/.venv
COPY pyproject.toml /project/

ENTRYPOINT pdm start